
title: Xueqian Li
url: ''
baseurl: '' #change it according to your repository name


# Profile information
yourname: Xueqian Li  ## put your name
title: 'HH'  ## your title
location: Pittsburgh, PA


## Social Profiles
CV: ## link of the file
googlescholar: https://scholar.google.com/citations?user=aNnRnv0AAAAJ&hl=en ## google scholar account
github: https://github.com/Lilac-Lee ## github account
linkedin: http://www.linkedin.com  ## your linkedin account url


# Update all the sections by editing the files inside _includes folder.
