
title: Xueqian Li
url: ''
baseurl: '' #change it according to your repository name


# Profile information
yourname: Xueqian Li  ## put your name
title: 'HH'  ## your title
location: Pittsburgh, PA


## Social Profiles
linkedin: http://www.linkedin.com  ## your linkedin account url


# Update all the sections by editing the files inside _includes folder.
